repair shellcheck action for Markdown snippets
Signed-off-by: Lucas Larson <LucasLarson@riseup.net>

diff --git a/.github/workflows/shellcheck-markdown.yml b/.github/workflows/shellcheck-markdown.yml
--- a/.github/workflows/shellcheck-markdown.yml
+++ b/.github/workflows/shellcheck-markdown.yml
@@ -17,70 +17,59 @@ jobs:
           # test shell syntax of Markdown code snippets
           # https://github.com/dylanaraps/pure-sh-bible/commit/9d54e96011
 
-          trap 'printf -- "shellcheck complete\n"' EXIT INT
+          # Markdown filename extensions
+          # github/linguist@7503f7588c/lib/linguist/languages.yml#L3707-L3718
+          command find -- . \
+            '(' \
+            -name '*.md' -o \
+            -name '*.livemd' -o \
+            -name '*.markdown' -o \
+            -name '*.mdown' -o \
+            -name '*.mdwn' -o \
+            -name '*.mdx' -o \
+            -name '*.mkd' -o \
+            -name '*.mkdn' -o \
+            -name '*.mkdown' -o \
+            -name '*.ronn' -o \
+            -name '*.scd' -o \
+            -name '*.workbook' -o \
+            -name 'contents.lr' \
+            ')' \
+            -type f \
+            -exec sh -v -c '
+            command git ls-files --error-unmatch -- "${1-}" >/dev/null 2>&1 ||
+            ! command git rev-parse --is-inside-work-tree >/dev/null 2>&1 &&
+            while IFS='\'''\'' read -r line; do
+              command test "${code-}" = 1 &&
+                command test "${line-}" != '\''```'\'' &&
+                command printf -- '\''%s\n'\'' "${line-}"
 
-          # Extract code blocks from the README.
-          while IFS='' read -r line; do
-            test "${code-}" = '1' &&
-              test "${line-}" != '```' &&
-              printf -- '%s\n' "${line-}"
+              case "${line-}" in
+              '\''```sh'\''|'\''```bash'\''|'\''```shell'\''|'\''```zsh'\'')
+                code=1
+                ;;
+              '\''```'\'')
+                code='\'''\''
+                ;;
+              *) ;;
 
-            case "${line-}" in
-            '```sh' | '```bash' | '```zsh' | '```shell')
-              code='1'
-              ;;
-            '```')
-              code=''
-              ;;
-            *) ;;
+              esac
 
-            esac
-          done < <(
-            # Markdown filename extensions
-            # https://github.com/github/linguist/blob/7503f7588c/lib/linguist/languages.yml#L3707-L3718
-            command find -- . \
-              -name '*.md' -o \
-              -name 'contents.lr' -o \
-              -name '*.livemd' -o \
-              -name '*.markdown' -o \
-              -name '*.mdown' -o \
-              -name '*.mdwn' -o \
-              -name '*.mdx' -o \
-              -name '*.mkd' -o \
-              -name '*.mkdn' -o \
-              -name '*.mkdown' -o \
-              -name '*.ronn' -o \
-              -name '*.scd' -o \
-              -name '*.workbook'
-          ) >'./codesnippets_code'
-
-          # Print the code blocks.
-          while IFS='' read -r line; do
-            printf -- '%s\n' "${line-}"
-          done <'./codesnippets_code'
-
-          # Run shellcheck on the extracted code blocks
-          # and this test script itself.
-
-          # SC1071: allow shell directives outside sh, bash, ksh, dash
-          # SC1090: allow linking to a dynamic location
-          # SC1091: allow linking to, but not following, linked scripts
-          # SC2123: allow `PATH=...`
-          # SC2312: allow masking of return values
-          command shellcheck \
-            --exclude="SC1071,SC1090,SC1091,SC2123,SC2312" \
-            --wiki-link-count="$(command getconf -- UINT_MAX)" \
-            --check-sourced \
-            --enable=all \
-            --source-path=/dev/null \
-            --external-sources \
-            --include="" \
-            --shell=bash \
-            --severity=style \
-            --norc \
-            --color=always \
-            -- \
-            ./codesnippets_code \
-            "$0" ||
-            exit 1
+              # SC1071: allow shell directives outside sh, bash, ksh, dash
+              # SC1090: allow linking to a dynamic location
+              # SC1091: allow linking to, but not following, linked scripts
+              # SC2123: allow `PATH=...`
+              # SC2312: allow masking of return values
+            done <"${1-}"' _ {} ';' |
+            command shellcheck \
+              --check-sourced \
+              --enable=all \
+              --exclude='SC1071,SC1090,SC1091,SC2123,SC2312' \
+              --norc \
+              --severity=style \
+              --shell=sh \
+              --source-path=/dev/null \
+              -- \
+              - ||
+              exit "${?:-1}"
 ...
